apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order-service:latest
        imagePullPolicy: "Never"
        env:
          - name: AppPort
            value: "3000"
          - name: DaraSourceUrl
            value: root:s3cr3t@tcp(order-db:3306)/order
          - name:  Env
            value: dev
          - name: PaymentServiceUrl
            value: payment-app:3001
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

